{{ "{%" }} set version = "{{ cookiecutter.module_version }}" {{ "%}" }}
{{ "{%" }} set name = "{{ cookiecutter.module_name }}" {{ "%}" }}

package:
{%- raw %}
  name: "{{ name|lower }}"
  version: "{{ version }}"
{%- endraw %}

source:
{%- raw %}
  - url: {{ cookiecutter.module_url }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: ""
{%- endraw %}
  - path: ../src

build:
  number: 0
  run_exports:
{%- raw %}
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}
{%- endraw %}

requirements:
  build:
{%- raw %}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - perl
{%- endraw %}
  host:
    - epics-base
    - require

test:
{%- raw %}
  requires:
    - run-iocsh
  commands:
    - run-iocsh -r {{ name|lower }}
{%- endraw %}

about:
  home: "{{ cookiecutter.module_url }}"
  license: {{ cookiecutter.module_license }}
  license_file: {{ cookiecutter.module_license_file }}
  summary: "{{ cookiecutter.summary }}"
