# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# The final recipe shouldn't contain any comments!

{{ "{%" }} set version = "{{ cookiecutter.module_version }}" {{ "%}" }}

package:
  # Name shall be in lowercase!
  name: {{ cookiecutter.module_name | lower }}
{%- raw %}
  version: "{{ version }}"
{%- endraw %}

source:
  # Getting the source from an archive is the preferred way
  # If required, you can use the git_url and git_rev instead
{%- if cookiecutter.module_home == "github.com" %}
  - url: https://github.com/epics-modules/{{ cookiecutter.module_name }}/archive/xxx.tar.gz
{%- elif cookiecutter.module_home == "gitlab.esss.lu.se" %}
  - url: https://gitlab.esss.lu.se/epics-modules/{{ cookiecutter.module_name }}/-/archive/v{{ '{{' }} version {{ '}}' }}/{{ cookiecutter.module_name }}-v{{ '{{' }} version {{ '}}' }}.tar.gz
{%- endif %}
    sha256: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # sha256 is the prefered checksum -- you can get it for a file with:
    # `openssl sha256 <file name>`.
#  - git_url: https://github.com/epics-modules/{{ cookiecutter.module_name }}.git
{%- raw %}
#    git_rev: "v{{ version }}"
{%- endraw %}
  # Extra source files (Makefile, iocsh) should be copied under the ../src directory
  - path: ../src

build:
  # Uncomment the skip line to disable ppc64 cross-compilation
  # Or use [not ppc64] to only compile for ppc64
  # Remove this line otherwise
  # skip: True  # [ppc64]
  number: 0
  run_exports:
    - {{ "{{" }} pin_subpackage('{{ cookiecutter.module_name | lower }}', max_pin='x.x.x.x') {{ "}}" }}

requirements:
  build:
{%- raw %}
    - make
    - perl
    - tclx
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
{%- endraw %}
  host:
    - epics-base
    - require

test:
  requires:
    - run-iocsh
  source_files:
    - cmds/*.cmd
  commands:
    # Loading the module with -r is the most basic test that should be done
    - run-iocsh -r {{ cookiecutter.module_name | lower }}
    # Keep the following line only if you have a test command file
    - run-iocsh cmds/test.cmd

about:
  home: "https://{{ cookiecutter.module_home }}/epics-modules/{{ cookiecutter.module_name }}"
  license: EPICS Open License
  # Many licenses require the license statement to be distributed with the package.
  # The filename is relative to the source directory
  license_file: LICENSE
  summary: "{{ cookiecutter.summary }}"
